# Generated by Django 4.2.11 on 2024-08-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Simulator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("text", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("desc", models.CharField(max_length=255)),
                ("correct_answer", models.IntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_questions",
                        to="Simulator.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order"],
                "unique_together": {("chapter", "order")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_desc", models.CharField(max_length=50)),
                ("time", models.FloatField()),
                ("question_cnt", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of the chapter in the test"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_order",
                        to="Simulator.chapter",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Simulator.test"
                    ),
                ),
            ],
            options={
                "ordering": ["test", "order"],
                "unique_together": {("test", "chapter")},
            },
        ),
        migrations.AddField(
            model_name="test",
            name="chapters",
            field=models.ManyToManyField(
                through="Simulator.TestChapter", to="Simulator.chapter"
            ),
        ),
        migrations.CreateModel(
            name="StudentAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_number",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4")]
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_questions",
                        to="Simulator.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_tests",
                        to="Simulator.test",
                    ),
                ),
            ],
            options={"ordering": ["student", "test", "question"],},
        ),
        migrations.AddField(
            model_name="chapter",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_chapters",
                to="Simulator.subject",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("desc", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_answers",
                        to="Simulator.question",
                    ),
                ),
            ],
            options={"ordering": ["question", "order"],},
        ),
    ]
