# Generated by Django 4.2.11 on 2024-09-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Simulator", "0003_user_gender_user_joining_date_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentanswers", options={"ordering": ["student", "question"]},
        ),
        migrations.RemoveField(model_name="studentanswers", name="test",),
    ]
