# Generated by Django 4.2.11 on 2024-09-05 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Simulator", "0004_alter_studentanswers_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSimulator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simulator_number", models.PositiveIntegerField()),
                ("date_taken", models.DateField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
