# Generated by Django 4.2.11 on 2024-09-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Simulator", "0005_studentsimulator"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanswers",
            name="simulator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="Simulator.studentsimulator",
            ),
            preserve_default=False,
        ),
    ]
